### ISSUE TITLE
Compatibility issue with UltraVNC viewer

### ISSUE THREAD

**Issue by wqweto** [any1/neatvnc#108]
I recently stumbled on the fact that in `RFB_CLIENT_TO_SERVER_SET_ENCODINGS` message UltraVNC client sometimes sends more that 32 (pseudo-)encodings.

In this case there is a problem in `on_client_set_encodings` function in `server.c` because there is [this](https://github.com/any1/neatvnc/blob/ddd5ee123e28a57b870d3d1d3569d9d6409fef1a/src/server.c#L947C1-L947C67) check
```
	size_t n_encodings = MIN(MAX_ENCODINGS, ntohs(msg->n_encodings));
```
. . . and the incoming `msg->n_encodings` count is limited up to 32 encodings.

Probably `MAX_ENCODINGS` limit should be checked on *accepted* encodings in `client->encodings` array as it is [sized](https://github.com/any1/neatvnc/blob/ddd5ee123e28a57b870d3d1d3569d9d6409fef1a/include/common.h#L91) to `MAX_ENCODINGS + 1` elements which will allow incoming number of encodings to be above `MAX_ENCODINGS` limit as this is harmless.

The issue is exacerbated because `on_client_set_encodings` returns `sizeof(*msg) + 4 * n_encodings` but `n_encodings` is trimmed above at 32 so the effect is that next message is started from inside incompletely parsed `RFB_CLIENT_TO_SERVER_SET_ENCODINGS` data and is usually invalid type so client connection gets closed.

**Comment by any1** [comment]
> Probably MAX_ENCODINGS limit should be checked on accepted encodings in client->encodings array as it is sized to MAX_ENCODINGS + 1 elements which will allow incoming number of encodings to be above MAX_ENCODINGS limit as this is harmless.

Yep, that's a good idea.

**Comment by any1** [comment]
@wqweto, can you confirm that the issue is fixed?

**Comment by wqweto** [comment]
Yes, just tested the fix is working ok with 33 encodings sent from UltraVNC client.
