### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by any1** [any1/neatvnc#2]
It would be convenient to have Websocket support build in for noVNC.

**Comment by braderhart** [comment]
This is necessary for proper noVNC support, which would be great for building a Wayland-compatible web-based remote desktop solution. Any chance you can prioritize support for it?

**Comment by any1** [comment]
Well, it's a hobby project, so I prioritise based on fun-factor. PRs are welcome. :)

**Comment by braderhart** [comment]
That is totally fair and wish I could do it myself, but your coding skills are far superior than mine. I appreciate you adding the enhancement issue and maybe one day I'll find the time/money to make it happen if it is that important to me personally, or you or someone else will. Cheers.

**Comment by any1** [comment]
I could guide you if you want. Stop by on `#wayvnc` on freenode if you're interested.

**Comment by braderhart** [comment]
Thanks, I think I'll try to take you up on that offer real soon.
