### ISSUE TITLE
999c1ef255 breaks remmina

### ISSUE THREAD

**Issue by myfreeweb** [any1/neatvnc#25]
I'm not sure what exactly is to blame, but commit 999c1ef255ee58e4d04b08f8699d36bfccf67692 "tight: Limit rectangle max width according to spec" breaks my connection from Remmina 1.3.9 (the viewer window instantly closes, showing maybe one frame).

**Comment by any1** [comment]
Do you have a 4K monitor?

**Comment by myfreeweb** [comment]
Yes, but on the client. The server is 2400x1600. I'll try updating remmina just in case..

**Comment by any1** [comment]
I see. I didn't test this, actually. And I see the problem now. The extra rectangle is not included in the count that's sent beforehand.

**Comment by any1** [comment]
I reverted the change. Maybe clients don't actually care about this limit.

**Comment by any1** [comment]
Should be fixed now.
