### ISSUE TITLE
wayvnc incorrectly negotiates tight encoding when resolution is too large for it

### ISSUE THREAD

**Issue by colemickens** [any1/neatvnc#36]
See: https://github.com/TigerVNC/tigervnc/issues/1054#event-3505527978

It appears the server might not be following spec in regards to advertising encodings available for a given remote resolution.

**Comment by any1** [comment]
This is related to #25

**Comment by any1** [comment]
I've been working a new tight encoder that breaks the surface up into tiles and splits up encoding of the tiles between threads: https://github.com/any1/neatvnc/tree/tight-encoder-v2

The new encoder should also fix this issue.

**Comment by any1** [comment]
tight encoder v2 is now merged into master, so this should no longer be a problem.
