### ISSUE TITLE
Add `aml` as a git submodule

### ISSUE THREAD

**Issue by hexcowboy** [any1/neatvnc#52]
Adding dependency `aml` as a submodule would simplify the build procedure.

Instead of
```bash
git clone "https://github.com/any1/neatvnc.git"
cd neatvnc
mkdir subprojects
cd subprojects
git clone https://github.com/any1/aml.git
cd ..
meson build
```

A submodule can be installed
```bash
git clone "https://github.com/any1/neatvnc.git"
cd neatvnc
git submodule update --init --recursive
meson build
```

I can create a PR if this project is willing to accept this improvement.

**Comment by any1** [comment]
If we do that, then we have to update the submodule ref every time that a change is made to master. Submodules might be slightly nicer for people who just want to build from source, but other than that, they just get in my way.

**Comment by hexcowboy** [comment]
Understood. Closing for now
